### PR TITLE
Add 65CE02 opcodes

### PR DESCRIPTION
**Pull request by mlund**
This adds opcodes for the 65CE02 processor. ~Currently this is a draft PR and is under development as I still haven't figured out how to use the `Opcode<>()` function for 2 and 3 byte opcodes~.

- [x] Add `bool Has65CE02()` and related infrastructure
- [x] Tests in `test/MC/MOS/all-65ce02-opcodes.s`
- [x] Nearly complete set of 65CE02 opcodes, except `AUG`
- [x] Add additional 65C02 opcodes
- [x] Resolve decoding conflicts with 65816
- [x] Passes `ninja check-llvm-mc-mos check-llvm-codegen-mos check-llvm-debuginfo-mos`.
- [x] (Dis)assembler round-trip OK

Notes:
- See http://archive.6502.org/datasheets/mos_65ce02_mpu.pdf
- The stack pointer is optionally 16-bit on the 65CE02
- Rename functions `_ZeroPage` to `_BasePage`?

Related to #54.

### CODE REVIEW

**Comment by johnwbyrd** [comment]
"Per Parker" just means "According to Parker."  I'll review the rest of this in a day or two.

**Comment by johnwbyrd** [comment]
I've done some spot checking, and I think I'm seeing some errors in your tables.  Opcode sse should be opcode see; what you have for bra $eaea is actually bru $eaea.  Personally, I find that sorting by opcode in all-65ce02-opcodes can make it easier to compare against known good sources, such as those from cc65.  Thoughts?

**Comment by mlund** [comment]
I fixed the SSE typo and sorted opcodes in the tests. The 65c02 0x80 opcode was already called BRA which is why I labeled 0x83 the same. I'm happy to rename to BRU, but then we should probably do the same for 0x80. KickC and CA65 calls both "BRA"; in the MOS data sheet it's "BRU (BRA)"

**Comment by johnwbyrd** [comment]
I'm getting a lot of decoding conflicts when building MOSGenDisassemberTables.inc, in the new instructions that you've added for the 65ce02 instruction set.  Are you seeing those while building your pull request?  For example, RTL_Implied and TZA_Implied, ORA_Indirect and ORA_IndirectZeroPageZ.  It's necessary to fix these to get the disassembler to work correctly.

**Comment by mlund** [comment]
> I'm getting a lot of decoding conflicts when building MOSGenDisassemberTables.inc, in the new instructions that you've added for the 65ce02 instruction set. Are you seeing those while building your pull request? For example, RTL_Implied and TZA_Implied, ORA_Indirect and ORA_IndirectZeroPageZ. It's necessary to fix these to get the disassembler to work correctly.

Yes, I see them. It seems to be overlaps with the 65816 target. The 65ce02 should not get mixed with that, but I don't know how to disable it.

**Comment by johnwbyrd** [comment]
See https://lists.llvm.org/pipermail/llvm-dev/2020-August/144576.html for some hints on how to do this.

**Comment by mlund** [comment]
> I'll let this through, if you are willing to focus next on getting disassembly working for 65CE02. It should be possible to use llvm-mc -assemble followed by llvm-mc -disassemble on assembly source code to get the same input file on 65CE02. What do you say?

Let me give this a go on and see if I can get this working on 65ce02-specific instructions. If so we can include it in this PR, then create a fresh one focusing on disassembler test across all architectures. OK?

**Comment by johnwbyrd** [comment]
FAIL: lld :: ELF/basic-mos.s (655 of 2643)
******************** TEST 'lld :: ELF/basic-mos.s' FAILED ********************
Script:
--
: 'RUN: at line 3';   /Users/runner/work/llvm-mos/llvm-mos/build/bin/llvm-mc -filetype=obj -triple=mos /Users/runner/work/llvm-mos/llvm-mos/lld/test/ELF/basic-mos.s -o /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.o.6502
: 'RUN: at line 4';   /Users/runner/work/llvm-mos/llvm-mos/build/bin/ld.lld /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.o.6502 -o /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.6502
: 'RUN: at line 5';   /Users/runner/work/llvm-mos/llvm-mos/build/bin/llvm-readobj --file-headers --sections -l /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.6502 | /Users/runner/work/llvm-mos/llvm-mos/build/bin/FileCheck /Users/runner/work/llvm-mos/llvm-mos/lld/test/ELF/basic-mos.s -check-prefixes=CHECK,6502
: 'RUN: at line 7';   /Users/runner/work/llvm-mos/llvm-mos/build/bin/llvm-mc -filetype=obj -triple=mos -mcpu=mos6502x /Users/runner/work/llvm-mos/llvm-mos/lld/test/ELF/basic-mos.s -o /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.o.6502x
: 'RUN: at line 8';   /Users/runner/work/llvm-mos/llvm-mos/build/bin/ld.lld /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.o.6502x -o /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.6502x
: 'RUN: at line 9';   /Users/runner/work/llvm-mos/llvm-mos/build/bin/llvm-readobj --file-headers --sections -l /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.6502x | /Users/runner/work/llvm-mos/llvm-mos/build/bin/FileCheck /Users/runner/work/llvm-mos/llvm-mos/lld/test/ELF/basic-mos.s -check-prefixes=CHECK,6502X
: 'RUN: at line 11';   /Users/runner/work/llvm-mos/llvm-mos/build/bin/llvm-mc -filetype=obj -triple=mos -mcpu=mos65c02 /Users/runner/work/llvm-mos/llvm-mos/lld/test/ELF/basic-mos.s -o /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.o.65c02
: 'RUN: at line 12';   /Users/runner/work/llvm-mos/llvm-mos/build/bin/ld.lld /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.o.65c02 -o /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.65c02
: 'RUN: at line 13';   /Users/runner/work/llvm-mos/llvm-mos/build/bin/llvm-readobj --file-headers --sections -l /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.65c02 | /Users/runner/work/llvm-mos/llvm-mos/build/bin/FileCheck /Users/runner/work/llvm-mos/llvm-mos/lld/test/ELF/basic-mos.s -check-prefixes=CHECK,65C02
: 'RUN: at line 15';   /Users/runner/work/llvm-mos/llvm-mos/build/bin/llvm-mc -filetype=obj -triple=mos -mcpu=mosr65c02 /Users/runner/work/llvm-mos/llvm-mos/lld/test/ELF/basic-mos.s -o /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.o.r65c02
: 'RUN: at line 16';   /Users/runner/work/llvm-mos/llvm-mos/build/bin/ld.lld /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.o.r65c02 -o /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.r65c02
: 'RUN: at line 17';   /Users/runner/work/llvm-mos/llvm-mos/build/bin/llvm-readobj --file-headers --sections -l /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.r65c02 | /Users/runner/work/llvm-mos/llvm-mos/build/bin/FileCheck /Users/runner/work/llvm-mos/llvm-mos/lld/test/ELF/basic-mos.s -check-prefixes=CHECK,R65C02
: 'RUN: at line 19';   /Users/runner/work/llvm-mos/llvm-mos/build/bin/llvm-mc -filetype=obj -triple=mos -mcpu=mosw65c02 /Users/runner/work/llvm-mos/llvm-mos/lld/test/ELF/basic-mos.s -o /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.o.w65c02
: 'RUN: at line 20';   /Users/runner/work/llvm-mos/llvm-mos/build/bin/ld.lld /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.o.w65c02 -o /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.w65c02
: 'RUN: at line 21';   /Users/runner/work/llvm-mos/llvm-mos/build/bin/llvm-readobj --file-headers --sections -l /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.w65c02 | /Users/runner/work/llvm-mos/llvm-mos/build/bin/FileCheck /Users/runner/work/llvm-mos/llvm-mos/lld/test/ELF/basic-mos.s -check-prefixes=CHECK,W65C02
: 'RUN: at line 23';   /Users/runner/work/llvm-mos/llvm-mos/build/bin/llvm-mc -filetype=obj -triple=mos -mcpu=mosw65816 /Users/runner/work/llvm-mos/llvm-mos/lld/test/ELF/basic-mos.s -o /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.o.w65816
: 'RUN: at line 24';   /Users/runner/work/llvm-mos/llvm-mos/build/bin/ld.lld /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.o.w65816 -o /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.w65816
: 'RUN: at line 25';   /Users/runner/work/llvm-mos/llvm-mos/build/bin/llvm-readobj --file-headers --sections -l /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.w65816 | /Users/runner/work/llvm-mos/llvm-mos/build/bin/FileCheck /Users/runner/work/llvm-mos/llvm-mos/lld/test/ELF/basic-mos.s -check-prefixes=CHECK,W65816
: 'RUN: at line 27';   /Users/runner/work/llvm-mos/llvm-mos/build/bin/llvm-mc -filetype=obj -triple=mos -mcpu=mosw65el02 /Users/runner/work/llvm-mos/llvm-mos/lld/test/ELF/basic-mos.s -o /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.o.65el02
: 'RUN: at line 28';   /Users/runner/work/llvm-mos/llvm-mos/build/bin/ld.lld /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.o.65el02 -o /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.65el02
: 'RUN: at line 29';   /Users/runner/work/llvm-mos/llvm-mos/build/bin/llvm-readobj --file-headers --sections -l /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.65el02 | /Users/runner/work/llvm-mos/llvm-mos/build/bin/FileCheck /Users/runner/work/llvm-mos/llvm-mos/lld/test/ELF/basic-mos.s -check-prefixes=CHECK,65EL02
: 'RUN: at line 31';   /Users/runner/work/llvm-mos/llvm-mos/build/bin/llvm-mc -filetype=obj -triple=mos -mcpu=mosw65ce02 /Users/runner/work/llvm-mos/llvm-mos/lld/test/ELF/basic-mos.s -o /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.o.65ce02
: 'RUN: at line 32';   /Users/runner/work/llvm-mos/llvm-mos/build/bin/ld.lld /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.o.65ce02 -o /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.65ce02
: 'RUN: at line 33';   /Users/runner/work/llvm-mos/llvm-mos/build/bin/llvm-readobj --file-headers --sections -l /Users/runner/work/llvm-mos/llvm-mos/build/tools/lld/test/ELF/Output/basic-mos.s.tmp.65ce02 | /Users/runner/work/llvm-mos/llvm-mos/build/bin/FileCheck /Users/runner/work/llvm-mos/llvm-mos/lld/test/ELF/basic-mos.s -check-prefixes=CHECK,65CE02
--
Exit Code: 1
Command Output (stderr):
--
'mosw65ce02' is not a recognized processor for this target (ignoring processor)
'mosw65ce02' is not a recognized processor for this target (ignoring processor)
/Users/runner/work/llvm-mos/llvm-mos/lld/test/ELF/basic-mos.s:38:3: error: instruction requires a CPU feature not currently enabled
  lda #42
  ^
/Users/runner/work/llvm-mos/llvm-mos/lld/test/ELF/basic-mos.s:39:3: error: instruction requires a CPU feature not currently enabled
  rts
  ^

**Comment by johnwbyrd** [comment]
Thanks!

**Comment by johnwbyrd** [comment]
Thanks for working so hard to get this merged.

**Pull request merged**
