### PR TITLE
Implement structured bindings in for-loops. NFC.

### PR DESCRIPTION
**Pull request by gandhi56**

### CODE REVIEW

**Comment by mysterymath** [comment]
For this change, we're waiting for the LLVM style guide to accept C++17 features. (See https://llvm.org/docs/CodingStandards.html#c-standard-versions). This typically lags a bit behind the current standard to allow LLVM to compile with older GCC and LLVM versions. We're trying to keep our style guide in line with LLVM's to ease upstreaming of any patches made against llvm-mos.

**Comment by gandhi56** [comment]
Is LLVM officially accepting C++17 now after [D130689](https://reviews.llvm.org/D130689) ? :)

**Comment by mysterymath** [comment]
Hah, looks like! I'll have to do a pull sometime soon.

**Comment by mysterymath** [comment]
Actually, looks like it's accepted, but not submitted yet.

**Comment by mysterymath** [comment]
The upstream patch to accept C++17 has now landed, and I've finished pulling from upstream. You can now go ahead with this PR.

**Comment by gandhi56** [comment]
Opened #219

**Pull request closed without merging**
